# ================================================================
# GENERATIVE AI PRACTICAL - 01
# Aim: To study the concept of Generative Artificial Intelligence
#      and compare Generative Models with Discriminative Models.
# Roll No.: BT24S05F006
# ================================================================

# Required libraries:
# pip install numpy matplotlib scikit-learn

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.mixture import GaussianMixture
from sklearn.metrics import accuracy_score, classification_report
from sklearn.decomposition import PCA


# ------------------------------------------------
# 1. Introduction / Theory
# ------------------------------------------------
# Generative models learn the underlying distribution of data
# and can generate new samples.
#
# Discriminative models learn the relationship between input
# features and class labels and are commonly used for prediction.
#
# In this practical:
#   - Logistic Regression -> Discriminative model
#   - Gaussian Mixture Model (GMM) -> Generative model
#
# The sklearn Digits dataset is used as a small handwritten-digit
# image dataset (8 x 8 images, 10 classes).


# ------------------------------------------------
# 2. Load the dataset
# ------------------------------------------------
digits = load_digits()

X = digits.data
y = digits.target

print("=" * 60)
print("GENERATIVE AI VS DISCRIMINATIVE MODELS")
print("=" * 60)
print("Dataset shape:", X.shape)
print("Number of classes:", len(np.unique(y)))
print("Image size:", digits.images.shape[1], "x", digits.images.shape[2])


# Display sample digit images
fig, axes = plt.subplots(2, 5, figsize=(10, 4))

for ax, image, label in zip(
    axes.ravel(), digits.images[:10], y[:10]
):
    ax.imshow(image, cmap="gray")
    ax.set_title(f"Digit: {label}")
    ax.axis("off")

plt.suptitle("Sample Handwritten Digits")
plt.tight_layout()
plt.show()


# ------------------------------------------------
# 3. Split data into training and testing sets
# ------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])


# ================================================================
# 4. DISCRIMINATIVE MODEL
# ================================================================
# Logistic Regression learns decision boundaries between classes.

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

classifier = LogisticRegression(max_iter=2000)

classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)

print("\n" + "=" * 60)
print("DISCRIMINATIVE MODEL: LOGISTIC REGRESSION")
print("=" * 60)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# ================================================================
# 5. GENERATIVE MODEL
# ================================================================
# Gaussian Mixture Model learns a probability distribution from
# the training data and can generate new samples.
#
# PCA is used first to reduce the 64-dimensional digit features
# to 20 dimensions, making GMM training more stable.

pca = PCA(n_components=20, random_state=42)

X_train_pca = pca.fit_transform(X_train)

gmm = GaussianMixture(
    n_components=10,
    covariance_type="diag",
    random_state=42
)

gmm.fit(X_train_pca)

# Generate 10 new synthetic samples
generated_pca, _ = gmm.sample(10)

generated_samples = pca.inverse_transform(generated_pca)

# Pixel values in the Digits dataset range approximately from 0 to 16.
generated_samples = np.clip(generated_samples, 0, 16)


print("\n" + "=" * 60)
print("GENERATIVE MODEL: GAUSSIAN MIXTURE MODEL")
print("=" * 60)
print("GMM training completed successfully.")
print("Number of generated samples:", len(generated_samples))


# Display generated samples
fig, axes = plt.subplots(2, 5, figsize=(10, 4))

for ax, sample in zip(axes.ravel(), generated_samples):
    ax.imshow(sample.reshape(8, 8), cmap="gray")
    ax.set_title("Generated")
    ax.axis("off")

plt.suptitle("Synthetic Digit Samples Generated by GMM")
plt.tight_layout()
plt.show()


# ------------------------------------------------
# 6. Comparison
# ------------------------------------------------
print("\n" + "=" * 60)
print("COMPARISON")
print("=" * 60)

print("""
Generative Model:
- Model used: Gaussian Mixture Model (GMM)
- Learns: Probability distribution of data
- Can: Generate new synthetic samples

Discriminative Model:
- Model used: Logistic Regression
- Learns: Decision boundary / relationship between X and y
- Can: Predict class labels
""")


# ------------------------------------------------
# 7. Observation
# ------------------------------------------------
print("OBSERVATION")
print("""
1. Logistic Regression successfully classifies handwritten digits.
2. GMM learns the distribution of the digit feature space.
3. GMM can generate new synthetic digit-like samples.
4. Generative and discriminative models have different objectives.
""")


# ------------------------------------------------
# 8. Conclusion
# ------------------------------------------------
print("CONCLUSION")
print("""
Generative models learn the underlying data distribution and can
produce new samples, whereas discriminative models focus on
predicting class labels. Thus, the practical demonstrates the
difference between generative and discriminative approaches.
""")
